### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by virusdefender** [BIGBALLON/qduoj_install_sh#1]
- [ ] 操作判断返回值，是否成功
- [ ] 使用root权限，修改目录权限
- [ ] 将oj代码和data等放在`/home`下一个单独文件夹中，安装文档也需要修改，这样更好些
- [ ] docker版本的nginx（待讨论）
- [ ] MySQL和判题密码随机生成就好，然后显示一下
- [x] `mkdir -p` 可以放在一行
- [ ] MySQL打算单独做一个版本，加入binlog，放在阿里云上，redis也使用阿里云的
- [ ] `docker-compose`里面MySQL密码和判题密码不再都使用`{YOUR_PASSWORD}`，方便写脚本

**Comment by virusdefender** [comment]
打算用Python重写了，有些东西不知道用shell怎么写，比如错误重试函数之类的。。

你怎么看

**Comment by BIGBALLON** [comment]
可以考虑重写。
还有就是判断某些软件或者依赖是否已经安装，安装过就直接跳过。
错误重试函数貌似我没有用过，靠谱自己实现一个这样的函数，应该也行。
